### ISSUE TITLE
doesn't do much

### ISSUE THREAD

**Issue by ghost** [chanonroy/netflix-smart-list#1]
:P

**Comment by chanonroy** [comment]
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> :P 

Work in progress haha

**Comment by ghost** [comment]
looks like a cool idea :)
